# Generated by Django 3.2 on 2021-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_pk',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
