# Generated by Django 3.2 on 2021-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0002_auto_20210422_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=50)),
                ('section_instructor', models.CharField(max_length=50)),
                ('section_ta', models.CharField(max_length=50)),
                ('lab_instructor', models.CharField(max_length=50)),
                ('lab_ta', models.CharField(max_length=50)),
            ],
        ),
    ]
