# Generated by Django 3.2 on 2021-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lab_instructor',
            new_name='section_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section_ta',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
