# Generated by Django 3.2 on 2021-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0004_auto_20210502_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ta_count',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
